server:
  port: 8080

spring:
  application:
    name: jukeboxApiImpl

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  context-path: /manage
