app:
  image: poc.raml/accounts-api.impl
  expose:
    - 8080
  external_links:
    - "consulcluster_consul_1:consul"
  restart: "unless-stopped"
  mem_limit: "256m"
  command: >
    /opt/containerbuddy/containerbuddy
    -config "{
      \"consul\" : \"consul:8500\",
      \"services\" : [
        {
          \"name\" : \"accounts-api\",
          \"port\" : 8080,
          \"health\": \"/usr/bin/curl --fail -s http://localhost:8080/manage/health\",
          \"poll\": 15,
          \"ttl\": 35
        }
      ]
    }"
    java -Djava.security.egd=file:/dev/./urandom -jar /app.jar

haproxy:
  image: frascuchon/consul-nginx
  ports:
    - "80:80"
    - "443:443"
  external_links:
    - "consulcluster_consul_1:consul"
  environment:
    SERVICE_NAME: accounts-api
  restart: "unless-stopped"
  mem_limit: "128m"
